/*
 * JSP generated by Resin-4.0.28 (built Fri, 08 Jun 2012 05:08:34 PDT)
 */

package _jsp._base;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.cni.fw.ff.dto.*;
import com.cni.fw.ff.dto.entity.*;
import com.cni.fw.ff.util.maker.*;
import com.cni.fw.ff.dto.support.*;
import com.cni.fw.ff.util.*;
import com.cni.fw.id.*;
import com.cni.fw.web.util.*;
import com.cni.fw.web.session.so.CommonSession;
import com.cni.fw.ff.common.SystemInfo;
import com.cni.fw.ff.conf.BaseConfig;
import java.util.logging.Logger;

public class _fw_0right__jsp extends com.cni.fw.arch.ArchJsp implements com.caucho.jsp.CauchoPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    CauseDTO input = getCauseDTO(request);
    EffectDTO output = getEffectDTO(request);
    CommonSession cs = null;
    if (input != null) {
		cs = input.getCommonSession();
    }
    String ctxPath = request.getContextPath();

    out.write(_jsp_string1, 0, _jsp_string1.length);
     setNoCache(response); 
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print(( SystemInfo.getVersion() ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print(( Identity.emailContact ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print(( SystemInfo.getLastUpdate() ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print(( SystemInfo.getLicenseInfo()));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print(( BaseConfig.getInstance().get("fw.mode") ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2856366979881442457L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.server.webapp.WebApp _caucho_getApplication()
  {
     return (com.caucho.server.webapp.WebApp) getServletConfig().getServletContext();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("base/fw_right.jsp"), 804734819063953872L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("base/include/ArchJsp.jspf"), -4082645001948788182L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string3 = "</h1></b> \r\n    	<br>\r\n    <font color=green size=5>For Developer !! <font>\r\n    		<br><br>\r\n    		<br><br><br>\r\n    	<font color=blue size=3>\r\n    	WinterMute, TA Team, R&D Center, Dongbu CNI\r\n    	<br><br><br>\r\n    	<font color=black size=2>Q&A : <u>".toCharArray();
    _jsp_string5 = "</font></b><br><br>\r\n    	<b><font color=blue size=2>* LICENSE : ".toCharArray();
    _jsp_string6 = "</font></b><br><br>\r\n    	<b><font color=RED size=2>* CONFIG : MODE=".toCharArray();
    _jsp_string4 = "</u></font>\r\n    	<br>\r\n    	<font color=black size=2>Homepage : <a href=\"#\" onclick=\"window.open('http://daframe.dongbucni.co.kr/cms/');return false;\" >daframe.dongbucni.co.kr</a></font>\r\n    	<br><br><br>\r\n    	<!--  \r\n    	<font color=\"red\"><b>LOG Tracking</b> &nbsp;Tx Id : </font><input name=\"txId\" type=\"text\" size=16 onKeyDown=\"onEnter();\"/> \r\n    	<br><font color=gray size=-1>* \ucc38\uace0:Log \uc124\uc815\uc5d0\uc11c FileAppender\ub97c \uc9c0\uc815\ud588\uc744 \uacbd\uc6b0\uc5d0\ub9cc \ub3d9\uc791\ud569\ub2c8\ub2e4.</font>\r\n    	-->\r\n    	<b><font color=black size=2>* Last Update Date : ".toCharArray();
    _jsp_string7 = "</font></b><br><br>\r\n    </td>\r\n  </tr>\r\n</table>\r\n</form>\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n\r\n\r\n\r\n<html>\r\n\r\n<style tyoe=\"text/css\">\r\nbody,td {font-size:9pt; font-family:\"\ub9d1\uc740 \uace0\ub515\"; text-decoration:none; color:#333333; line-height:14px;}\r\n}\r\n</style>\r\n\r\n<SCRIPT type=text/javascript>\r\n\r\nfunction onEnter() {\r\n	if (event.keyCode == 13) {\r\n		if (trackForm.txId.value.length < 1) {\r\n			alert(\"\ud2b8\ub798\ud0b9 \ub300\uc0c1 TX\ub97c \uc785\ub825\ud558\uc138\uc694!\");\r\n		} else {\r\n			trackForm.txId.value = trim(trackForm.txId.value);\r\n			//alert(\"[\"+trackForm.txId.value+\"]\");\r\n			trackForm.submit();\r\n		}\r\n	}\r\n}\r\n\r\nfunction trim(str){ \r\n	str = str.replace(/(^\\s*)|(\\s*$)/g,\"\"); \r\n	return str; \r\n} \r\n\r\nfunction lpad(input, len, ch){\r\n input = ''+input;\r\n var strlen = input.length;\r\n var ret = \"\";\r\n var plen = len - strlen;\r\n var pstr = \"\"; \r\n \r\n for (i=0; i<plen; ++i)\r\n {\r\n  pstr = pstr + ch;\r\n }\r\n ret = pstr + input; \r\n\r\n return ret;\r\n}\r\n\r\n</SCRIPT>\r\n\r\n<body bgcolor=\"#F0F3FA\" leftmargin=\"0\" topmargin=\"0\">\r\n<form name=trackForm action=\"ADM001.A05.cmd\" method=\"post\"  onsubmit=\"return false\"	target=right>	\r\n<table width=\"100%\" height=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"F0F3FA\">\r\n  <tr>\r\n    <td align=\"center\" valign=\"middle\" bgcolor=\"#FFFFFF\">\r\n    	<img src=\"img/DAFrameLogo1.jpg\">\r\n    	<u><h4>Welcome to Dongbu CNI Application Framework</h4></u><br>\r\n    	<h1>DAFrame ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
