/*
 * JSP generated by Resin-4.0.28 (built Fri, 08 Jun 2012 05:08:34 PDT)
 */

package _jsp._base;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.cni.fw.ff.dto.*;
import com.cni.fw.ff.dto.entity.*;
import com.cni.fw.ff.util.maker.*;
import com.cni.fw.ff.dto.support.*;
import com.cni.fw.ff.util.*;
import com.cni.fw.id.*;
import com.cni.fw.web.util.*;
import com.cni.fw.web.session.so.CommonSession;
import com.cni.fw.ff.common.SystemInfo;
import java.util.Iterator;

public class _fw_0db_0jdbcinfo__jsp extends com.cni.fw.arch.ArchJsp implements com.caucho.jsp.CauchoPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    CauseDTO input = getCauseDTO(request);
    EffectDTO output = getEffectDTO(request);
    CommonSession cs = null;
    if (input != null) {
		cs = input.getCommonSession();
    }
    String ctxPath = request.getContextPath();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print(( request.getContextPath() ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print(( request.getContextPath() ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
	MTO dbInfo = output.getMTO("DB_PRODUCT");
	MTO jdbcInfo = output.getMTO("JDBC_DRIVER");
	MTO transactionInfo = output.getMTO("TRANSACTION_ISOLATION_SUPPORT");

    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print(( dbInfo.get("NAME") ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print(( dbInfo.get("VERSION") ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print(( jdbcInfo.get("NAME") ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print(( jdbcInfo.get("VERSION") ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print(( jdbcInfo.get("URL") ));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print(( jdbcInfo.get("USER") ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
     if (BooleanMaker.make(transactionInfo.get("TRANSACTION_NONE"))) { 
    out.write(_jsp_string11, 0, _jsp_string11.length);
     } 
    out.write(_jsp_string12, 0, _jsp_string12.length);
     if (BooleanMaker.make(transactionInfo.get("TRANSACTION_READ_UNCOMMITTED"))) { 
    out.write(_jsp_string11, 0, _jsp_string11.length);
     } 
    out.write(_jsp_string13, 0, _jsp_string13.length);
     if (BooleanMaker.make(transactionInfo.get("TRANSACTION_READ_COMMITTED"))) { 
    out.write(_jsp_string11, 0, _jsp_string11.length);
     } 
    out.write(_jsp_string14, 0, _jsp_string14.length);
     if (BooleanMaker.make(transactionInfo.get("TRANSACTION_REPEATABLE_READ"))) { 
    out.write(_jsp_string11, 0, _jsp_string11.length);
     } 
    out.write(_jsp_string15, 0, _jsp_string15.length);
     if (BooleanMaker.make(transactionInfo.get("TRANSACTION_SERIALIZABLE"))) { 
    out.write(_jsp_string11, 0, _jsp_string11.length);
     } 
    out.write(_jsp_string16, 0, _jsp_string16.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -2856366979881442457L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.server.webapp.WebApp _caucho_getApplication()
  {
     return (com.caucho.server.webapp.WebApp) getServletConfig().getServletContext();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("base/fw_db_jdbcInfo.jsp"), 4204827754868475872L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("base/include/ArchJsp.jspf"), -4082645001948788182L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string15;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string13;
  private final static char []_jsp_string11;
  private final static char []_jsp_string12;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string4;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  static {
    _jsp_string5 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>DB Version</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string15 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>TRANSACTION_SERIALIZABLE</td>\r\n		<td bgcolor=\"FFFFFF\" align=center>".toCharArray();
    _jsp_string2 = "/base/css/cni.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string8 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>JDBC URL</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string3 = "/base/js/daf.js\"></script>\r\n\r\n".toCharArray();
    _jsp_string13 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>TRANSACTION_READ_COMMITTED</td>\r\n		<td bgcolor=\"FFFFFF\" align=center>".toCharArray();
    _jsp_string11 = "\uc9c0\uc6d0".toCharArray();
    _jsp_string12 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>TRANSACTION_READ_UNCOMMITTED</td>\r\n		<td bgcolor=\"FFFFFF\" align=center>".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n<link href=\"".toCharArray();
    _jsp_string7 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>JDBC Version</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string9 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>JDBC User</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string4 = "\r\n\r\n<b>&nbsp;* DB \uc815\ubcf4</u></b>\r\n<table width=\"500\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"B5D5E2\">\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left width=35%>DB Name</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string16 = "</td>\r\n	</tr>\r\n</table>\r\n<br>\r\n<hr>\r\n".toCharArray();
    _jsp_string6 = "</td>\r\n	</tr>\r\n</table>\r\n<br>\r\n\r\n<hr>\r\n<b>&nbsp;* JDBC \uc815\ubcf4</u></b>\r\n<table width=\"500\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"B5D5E2\">\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left width=35%>JDBC Name</td>\r\n		<td bgcolor=\"FFFFFF\" align=left>".toCharArray();
    _jsp_string10 = "</td>\r\n	</tr>\r\n</table>\r\n<br>\r\n\r\n<hr>\r\n<b>&nbsp;* Transaction Isolation \uc9c0\uc6d0 \uc815\ubcf4</u></b>\r\n<table width=\"500\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"B5D5E2\">\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left width=35%>TRANSACTION_NONE</td>\r\n		<td bgcolor=\"FFFFFF\" align=center>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string14 = "</td>\r\n	</tr>\r\n	<tr>\r\n		<td bgcolor=\"EAF3F8\" align=left>TRANSACTION_REPEATABLE_READ</td>\r\n		<td bgcolor=\"FFFFFF\" align=center>".toCharArray();
  }
}
